# Metrics Server Helm values
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

args:
  - --kubelet-preferred-address-types=InternalIP
  - --kubelet-use-node-status-port
  - --metric-resolution=15s

podDisruptionBudget:
  enabled: true
  minAvailable: 1

apiService:
  create: true
